# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pdflite',
                'doc_host': 'https://vedicreader.github.io',
                'git_url': 'https://github.com/vedicreader/pdflite',
                'lib_path': 'pdflite'},
  'syms': { 'pdflite.core': { 'pdflite.core.clean_md': ('core.html#clean_md', 'pdflite/core.py'),
                              'pdflite.core.fix_layout': ('core.html#fix_layout', 'pdflite/core.py'),
                              'pdflite.core.needs_ocr': ('core.html#needs_ocr', 'pdflite/core.py'),
                              'pdflite.core.ocr_parse': ('core.html#ocr_parse', 'pdflite/core.py'),
                              'pdflite.core.orphan_vals': ('core.html#orphan_vals', 'pdflite/core.py'),
                              'pdflite.core.oxide_parse': ('core.html#oxide_parse', 'pdflite/core.py'),
                              'pdflite.core.pdf_doc': ('core.html#pdf_doc', 'pdflite/core.py'),
                              'pdflite.core.pdf_md': ('core.html#pdf_md', 'pdflite/core.py'),
                              'pdflite.core.scrambled_layout': ('core.html#scrambled_layout', 'pdflite/core.py')}}}
