# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['pdf_doc', 'clean_md', 'orphan_vals', 'scrambled_layout', 'needs_ocr', 'fix_layout', 'ocr_parse', 'oxide_parse',
           'pdf_md']

# %% ../nbs/00_core.ipynb #1ede4332ce3b
import re
from pathlib import Path
from fastcore.all import L, fdelegates
from pdf_oxide import PdfDocument

# %% ../nbs/00_core.ipynb #4620d94de4dd
def pdf_doc(pdf:str|Path|bytes|PdfDocument) -> PdfDocument:
    'A `PdfDocument` from a path, bytes or one you already have.'
    if isinstance(pdf, PdfDocument): return pdf
    return PdfDocument.from_bytes(pdf) if isinstance(pdf, bytes) else PdfDocument(str(pdf))

# %% ../nbs/00_core.ipynb #79509bed4730
_CHROME = re.compile(r'Press enter or click to view [^\n]+\n?', re.I)

def clean_md(md:str,                       # markdown from a PDF page
             preserve_layout:bool=False    # keep indentation and space runs, which a table needs
) -> str:
    'Rejoin hyphenated words, drop reader chrome, collapse the whitespace conversion leaves behind.'
    md = _CHROME.sub('', md)
    md = re.sub(r'([a-z])-\n([a-z])', r'\1\2', md)    # "docu-\nment" is one word
    md = re.sub(r'([a-z])-\n([A-Z])', r'\1-\2', md)   # "co-\nOperative" keeps its hyphen
    if not preserve_layout:
        md = re.sub(r'^ +', '', md, flags=re.M)
        md = re.sub(r' {2,}', ' ', md)
    return re.sub(r'\n{3,}', '\n\n', md)

# %% ../nbs/00_core.ipynb #1eec80429e1e
_ORPHAN = re.compile(r'^[\$\-\s]*[\d,]+\.\d{2}\s*$', flags=re.M)

def orphan_vals(md:str) -> int:
    'Lines holding a money value and nothing else, which is what a reflowed column leaves behind.'
    return len(_ORPHAN.findall(md))

def scrambled_layout(md:str) -> bool:
    'True when the text layer is fine but conversion cut values loose from their labels.'
    return orphan_vals(md) > 0

def needs_ocr(md:str) -> bool:
    'True when pdf-oxide flagged the page as scanned, so there is no text layer to read.'
    return '> [OCR REQUIRED' in md.strip()

def fix_layout(pdf:PdfDocument,             # the document the page came from
               page:int,                    # 0-based page number
               md:str,                      # that page's markdown
               preserve_layout:bool=False
) -> str:
    'Swap a scrambled page for its plain-text layer, but only if that strands fewer values.'
    if not scrambled_layout(md): return md
    txt = clean_md(pdf.to_plain_text(page, preserve_layout), preserve_layout)
    return txt if txt.strip() and orphan_vals(txt) < orphan_vals(md) else md

# %% ../nbs/00_core.ipynb #d8c52185113a
def ocr_parse(pdf:str|Path|bytes|PdfDocument,   # the document to scan
              dpi:int=300,                      # 150 is readable, 300 is good
              extract_links:bool=True,
              **kw                              # forwarded to LiteParse (num_workers, ...)
):
    'Run OCR over a scanned PDF. Returns the LiteParse result, whose `.pages` carry the text.'
    try: from liteparse import LiteParse
    except ImportError as e: raise ImportError('OCR needs liteparse: pip install liteparse') from e
    doc = pdf_doc(pdf)
    return LiteParse(ocr_enabled=True, dpi=dpi, extract_links=extract_links, **kw).parse(doc.to_bytes())

def oxide_parse(pdf:str|Path|bytes|PdfDocument,
                out_path:str|Path=None,     # dir holding the image subdir; links are relative to it
                preserve_layout:bool=False,
                image_dir:str='images',     # subdir under `out_path` for extracted images
                **kw                        # forwarded to pdf-oxide
) -> tuple:
    'Every page as cleaned, layout-repaired markdown, and whether any page wants OCR.'
    doc = pdf_doc(pdf)
    imdir = Path(out_path or 'pdfs').resolve()/image_dir
    imdir.mkdir(exist_ok=True, parents=True)
    kw = dict(image_output_dir=str(imdir), include_images=True, embed_images=False, **kw)
    def page(i):
        md = clean_md(doc.to_markdown(i, preserve_layout, **kw), preserve_layout)
        return fix_layout(doc, i, md, preserve_layout).replace(f'{imdir}/', f'{image_dir}/')
    pages = [page(i) for i in range(int(doc.page_count))]
    return pages, any(needs_ocr(p) for p in pages)

@fdelegates(oxide_parse)
def pdf_md(pdf:str|Path|bytes|PdfDocument,
           out_path:str|Path=None,
           pages:bool=False,          # True for one entry per page, False for one joined string
           ocr:str='auto',            # auto | on | off. auto asks pdf-oxide whether the page is scanned
           preserve_layout:bool=False,
           **kw                       # forwarded to oxide_parse and, on the OCR path, LiteParse
) -> str|list:
    'A PDF as markdown, with layout repaired and OCR where the page was scanned.'
    md, scanned = oxide_parse(pdf, out_path, preserve_layout, **kw)
    if ocr == 'on' or (ocr == 'auto' and scanned):
        got = [clean_md(p.text, preserve_layout) for p in ocr_parse(pdf).pages]
        if ''.join(got).strip(): md = got     # an empty OCR pass is a failure, not a document
    return md if pages else '\n---\n'.join(md)
